# Form implementation generated from reading ui file 'uix_login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
from PyQt6.QtGui import QFont, QFontDatabase

dirnames = os.path.dirname(__file__)
id = QFontDatabase.addApplicationFont(os.path.join(dirnames,"ttf","idealist_sans.ttf"))
if id < 0: print("Error")
families = QFontDatabase.applicationFontFamilies(id)


class Ui_uix_login(object):
    def setupUi(self, uix_login):
        uix_login.setObjectName("uix_login")
        uix_login.resize(707, 263)
        uix_login.setMaximumSize(QtCore.QSize(707, 263))
        uix_login.setStyleSheet("background-color:white;")
        self.label = QtWidgets.QLabel(parent=uix_login)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/logoApp.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=uix_login)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 301, 41))
        font = QtGui.QFont(families)
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=uix_login)
        self.label_3.setGeometry(QtCore.QRect(360, 70, 131, 31))
        font = QtGui.QFont(families)
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=uix_login)
        self.label_4.setGeometry(QtCore.QRect(360, 120, 131, 31))
        font = QtGui.QFont(families)
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtUser = QtWidgets.QLineEdit(parent=uix_login)
        self.txtUser.setGeometry(QtCore.QRect(492, 70, 191, 31))
        font = QtGui.QFont(families)
        font.setPointSize(14)
        self.txtUser.setFont(font)
        self.txtUser.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtUser.setObjectName("txtUser")
        self.txtPass = QtWidgets.QLineEdit(parent=uix_login)
        self.txtPass.setGeometry(QtCore.QRect(490, 120, 191, 31))
        font = QtGui.QFont(families)

        font.setPointSize(14)
        self.txtPass.setFont(font)
        self.txtPass.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtPass.setObjectName("txtPass")
        self.btnAcceder = QtWidgets.QPushButton(parent=uix_login)
        self.btnAcceder.setGeometry(QtCore.QRect(430, 200, 191, 32))
        font = QtGui.QFont(families)

        font.setPointSize(15)
        self.btnAcceder.setFont(font)
        self.btnAcceder.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;\n"
"background-color:rgb(237,133,39);\n"
"color:white;")
        self.btnAcceder.setObjectName("btnAcceder")

        self.retranslateUi(uix_login)
        QtCore.QMetaObject.connectSlotsByName(uix_login)

    def retranslateUi(self, uix_login):
        _translate = QtCore.QCoreApplication.translate
        uix_login.setWindowTitle(_translate("uix_login", "TODOVENTAS - Inicio de sesión"))
        self.label_2.setText(_translate("uix_login", "Inicio de sesión"))
        self.label_3.setText(_translate("uix_login", "Usuario"))
        self.label_4.setText(_translate("uix_login", "Contraseña"))
        self.btnAcceder.setText(_translate("uix_login", "Acceder"))
