# Form implementation generated from reading ui file 'uix_login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
from librery.file_sources import file_sources



class Ui_uix_login(object):
    def setupUi(self, uix_login):
        sources = file_sources()
        uix_login.setObjectName("uix_login")
        uix_login.resize(707, 263)
        uix_login.setMaximumSize(QtCore.QSize(707, 263))
        uix_login.setStyleSheet("background-color:white;")
        self.label = QtWidgets.QLabel(parent=uix_login)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(sources.dirname_img,"logoApp.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=uix_login)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 301, 41))
        self.label_2.setFont(QtGui.QFont(sources.families, 25))
        self.label_2.setStyleSheet("color:black;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=uix_login)
        self.label_3.setGeometry(QtCore.QRect(370, 70, 131, 31))

        self.label_3.setFont(QtGui.QFont(sources.families, 16))
        self.label_3.setStyleSheet("color:black;")        
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=uix_login)
        self.label_4.setGeometry(QtCore.QRect(370, 120, 131, 31))

        self.label_4.setFont(QtGui.QFont(sources.families, 16))
        self.label_4.setStyleSheet("color:black;")        
        self.label_4.setObjectName("label_4")
        self.txtUser = QtWidgets.QLineEdit(parent=uix_login)
        self.txtUser.setGeometry(QtCore.QRect(492, 70, 191, 31))

        self.txtUser.setFont(QtGui.QFont(sources.families, 15))
        self.txtUser.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtUser.setObjectName("txtUser")
        self.txtPassword = QtWidgets.QLineEdit(parent=uix_login)
        self.txtPassword.setGeometry(QtCore.QRect(490, 120, 191, 31))
        self.txtPassword.setFont(QtGui.QFont(sources.families, 20))
        self.txtPassword.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.btnAcceder = QtWidgets.QPushButton(parent=uix_login)
        self.btnAcceder.setGeometry(QtCore.QRect(430, 200, 191, 32))

        self.btnAcceder.setFont(QtGui.QFont(sources.families,15))
        self.btnAcceder.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;\n"
"background-color:rgb(237,133,39);\n"
"color:white;")
        self.btnAcceder.setObjectName("btnAcceder")
        self.btnAcceder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))

        self.retranslateUi(uix_login)
        QtCore.QMetaObject.connectSlotsByName(uix_login)

    def retranslateUi(self, uix_login):
        _translate = QtCore.QCoreApplication.translate
        uix_login.setWindowTitle(_translate("uix_login", "TODOVENTAS - Inicio de sesión"))
        self.label_2.setText(_translate("uix_login", "Inicio de sesión"))
        self.label_3.setText(_translate("uix_login", "Usuario"))
        self.label_4.setText(_translate("uix_login", "Contraseña"))
        self.btnAcceder.setText(_translate("uix_login", "Acceder"))
