# Form implementation generated from reading ui file 'uix_information_company.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from file_sources import file_sources


class Ui_uix_information_company(object):
    def setupUi(self, uix_information_company):
        sources = file_sources()
        uix_information_company.setObjectName("uix_information_company")
        uix_information_company.resize(627, 403)
        uix_information_company.setStyleSheet("background-color:white;")
        self.label = QtWidgets.QLabel(parent=uix_information_company)
        self.label.setGeometry(QtCore.QRect(110, 10, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(38,171,147);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_3.setGeometry(QtCore.QRect(410, 50, 51, 31))
        self.label_3.setFont(QtGui.QFont(sources.families, 15))
        self.label_3.setObjectName("label_3")
        self.txtRFC = QtWidgets.QLineEdit(parent=uix_information_company)
        self.txtRFC.setGeometry(QtCore.QRect(460, 50, 131, 31))
        self.txtRFC.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtRFC.setText("")
        self.txtRFC.setObjectName("txtRFC")
        self.txtRSocial = QtWidgets.QLineEdit(parent=uix_information_company)
        self.txtRSocial.setGeometry(QtCore.QRect(130, 50, 251, 31))
        self.txtRSocial.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtRSocial.setText("")
        self.txtRSocial.setObjectName("txtRSocial")
        self.label_2 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.label_2.setFont(QtGui.QFont(sources.families, 15))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_4.setGeometry(QtCore.QRect(20, 89, 91, 31))
        self.label_4.setFont(QtGui.QFont(sources.families, 15))
        self.label_4.setObjectName("label_4")
        self.txtDireccion = QtWidgets.QLineEdit(parent=uix_information_company)
        self.txtDireccion.setGeometry(QtCore.QRect(130, 90, 461, 31))
        self.txtDireccion.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtDireccion.setText("")
        self.txtDireccion.setObjectName("txtDireccion")
        self.comboEstado = QtWidgets.QComboBox(parent=uix_information_company)
        self.comboEstado.setGeometry(QtCore.QRect(130, 170, 461, 26))
        self.comboEstado.setFont(QtGui.QFont(sources.families, 15))
        self.comboEstado.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.comboEstado.setEditable(False)
        self.comboEstado.setCurrentText("")
        self.comboEstado.setFrame(True)
        self.comboEstado.setObjectName("comboEstado")
        self.label_9 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 61, 31))
        self.label_9.setFont(QtGui.QFont(sources.families, 15))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_11.setGeometry(QtCore.QRect(20, 250, 91, 31))
        self.label_11.setFont(QtGui.QFont(sources.families, 15))
        self.label_11.setObjectName("label_11")
        self.comboMunicipio = QtWidgets.QComboBox(parent=uix_information_company)
        self.comboMunicipio.setGeometry(QtCore.QRect(130, 210, 461, 26))
        self.comboMunicipio.setFont(QtGui.QFont(sources.families, 15))
        self.comboMunicipio.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.comboMunicipio.setEditable(False)
        self.comboMunicipio.setObjectName("comboMunicipio")
        self.comboColonia = QtWidgets.QComboBox(parent=uix_information_company)
        self.comboColonia.setGeometry(QtCore.QRect(130, 250, 461, 26))
        self.comboColonia.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.comboColonia.setEditable(False)
        self.comboColonia.setObjectName("comboColonia")
        self.label_10 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_10.setGeometry(QtCore.QRect(20, 210, 91, 31))
        self.label_10.setFont(QtGui.QFont(sources.families, 15))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_12.setGeometry(QtCore.QRect(20, 290, 91, 31))
        self.label_12.setFont(QtGui.QFont(sources.families, 15))
        self.label_12.setObjectName("label_12")
        self.comboCodigoPostal = QtWidgets.QComboBox(parent=uix_information_company)
        self.comboCodigoPostal.setGeometry(QtCore.QRect(130, 290, 461, 26))
        self.comboCodigoPostal.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.comboCodigoPostal.setEditable(False)
        self.comboCodigoPostal.setObjectName("comboCodigoPostal")
        self.label_5 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.label_5.setFont(QtGui.QFont(sources.families, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=uix_information_company)
        self.label_6.setGeometry(QtCore.QRect(280, 130, 91, 31))
        self.label_6.setFont(QtGui.QFont(sources.families, 15))
        self.label_6.setObjectName("label_6")
        self.txtNint = QtWidgets.QLineEdit(parent=uix_information_company)
        self.txtNint.setGeometry(QtCore.QRect(370, 130, 113, 31))
        self.txtNint.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtNint.setObjectName("txtNint")
        self.txtNext = QtWidgets.QLineEdit(parent=uix_information_company)
        self.txtNext.setGeometry(QtCore.QRect(130, 130, 113, 31))
        self.txtNext.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;")
        self.txtNext.setObjectName("txtNext")
        self.btnCancelar = QtWidgets.QPushButton(parent=uix_information_company)
        self.btnCancelar.setGeometry(QtCore.QRect(90, 350, 113, 32))
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCancelar.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;\n"
"background-color:rgb(223,31,41);\n"
"color:white;")
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnAceptar = QtWidgets.QPushButton(parent=uix_information_company)
        self.btnAceptar.setGeometry(QtCore.QRect(430, 350, 113, 32))
        self.btnAceptar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAceptar.setStyleSheet("border-radius: 4px;\n"
"border:1px solid black;\n"
"background-color:rgb(237,133,39);\n"
"color:white;")
        self.btnAceptar.setObjectName("btnAceptar")

        self.retranslateUi(uix_information_company)
        QtCore.QMetaObject.connectSlotsByName(uix_information_company)
        uix_information_company.setTabOrder(self.txtRSocial, self.txtRFC)
        uix_information_company.setTabOrder(self.txtRFC, self.txtDireccion)
        uix_information_company.setTabOrder(self.txtDireccion, self.txtNext)
        uix_information_company.setTabOrder(self.txtNext, self.txtNint)
        uix_information_company.setTabOrder(self.txtNint, self.comboEstado)
        uix_information_company.setTabOrder(self.comboEstado, self.comboMunicipio)
        uix_information_company.setTabOrder(self.comboMunicipio, self.comboColonia)
        uix_information_company.setTabOrder(self.comboColonia, self.comboCodigoPostal)

    def retranslateUi(self, uix_information_company):
        _translate = QtCore.QCoreApplication.translate
        uix_information_company.setWindowTitle(_translate("uix_information_company", "Dialog"))
        self.label.setText(_translate("uix_information_company", "Informacion de empresa"))
        self.label_3.setText(_translate("uix_information_company", "R.F.C"))
        self.label_2.setText(_translate("uix_information_company", "Razon social"))
        self.label_4.setText(_translate("uix_information_company", "Dirección"))
        self.label_9.setText(_translate("uix_information_company", "Estado"))
        self.label_11.setText(_translate("uix_information_company", "Localidad"))
        self.label_10.setText(_translate("uix_information_company", "Municipio"))
        self.label_12.setText(_translate("uix_information_company", "Codigo Postal"))
        self.label_5.setText(_translate("uix_information_company", "Numero ext."))
        self.label_6.setText(_translate("uix_information_company", "Numero int."))
        self.btnCancelar.setText(_translate("uix_information_company", "Cancelar"))
        self.btnAceptar.setText(_translate("uix_information_company", "Aceptar"))
